version: '3.1'

services:
    mongodb_dhu_treehole:
      image: bitnami/mongodb:latest
      volumes:
        - ./mongo-data:/var/lib/mongodb/data
      ports:
        - 27017:27017

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
      hostname: elasticsearch
      environment:
        - discovery.type=single-node
      volumes:
        - ./esdata:/var/lib/elasticsearch/data/tree_hole
      ports:
        - 9200:9200

    kibana:
      image: docker.elastic.co/kibana/kibana:6.0.0
      ports:
        - 5601:5601
